// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5e3RZpNNi-0kUrALI4TJE6N4L_4h4M4A',
    appId: '1:979033506974:web:9a3042819c75fa3eae278f',
    messagingSenderId: '979033506974',
    projectId: 'courier-app-678ea',
    authDomain: 'courier-app-678ea.firebaseapp.com',
    storageBucket: 'courier-app-678ea.firebasestorage.app',
    measurementId: 'G-T8XSZHVESD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPYHpQ8z79s0WmzX4wKI88qyRR1macUdU',
    appId: '1:979033506974:android:72741d7c8a6a4fa3ae278f',
    messagingSenderId: '979033506974',
    projectId: 'courier-app-678ea',
    storageBucket: 'courier-app-678ea.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBOwNLG9GR88ZKmTrzFS0GgCQ7xCksGpgc',
    appId: '1:979033506974:ios:2f4c7f74d02225eaae278f',
    messagingSenderId: '979033506974',
    projectId: 'courier-app-678ea',
    storageBucket: 'courier-app-678ea.firebasestorage.app',
    iosBundleId: 'com.gozde.courierApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBOwNLG9GR88ZKmTrzFS0GgCQ7xCksGpgc',
    appId: '1:979033506974:ios:2f4c7f74d02225eaae278f',
    messagingSenderId: '979033506974',
    projectId: 'courier-app-678ea',
    storageBucket: 'courier-app-678ea.firebasestorage.app',
    iosBundleId: 'com.gozde.courierApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB5e3RZpNNi-0kUrALI4TJE6N4L_4h4M4A',
    appId: '1:979033506974:web:ebbcead2b2035d5cae278f',
    messagingSenderId: '979033506974',
    projectId: 'courier-app-678ea',
    authDomain: 'courier-app-678ea.firebaseapp.com',
    storageBucket: 'courier-app-678ea.firebasestorage.app',
    measurementId: 'G-3M8YEQX4HV',
  );
}
